name: Lint code
env:
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the ZeroForcing Docker image
        run: docker build . --file Dockerfile --tag "zeroforcing:${SHA}"
      - name: Install lint requirements & Lint Cython code
        run: |
            docker run --rm "zeroforcing:${SHA}" 'sage -pip install zeroforcing[lint] && cython-lint $(find zeroforcing/src -type f \( -iname \*.pyx -o -iname \*.pxd \))'
